### ISSUE TITLE
Why `./src/lib/server/db` as the default path for drizzle?

### ISSUE THREAD

**Issue by garysassano** [sveltejs/cli#185]
First time I see this `./src/lib/server` path. Was it used for anything else before? Also this path looks quite lengthy, not ideal in my opinion.

Why not simply use `./src/db` as the default path for drizzle and also set up a `$db` alias in the SvelteKit config?

**Comment by manuel3108** [comment]
I'm sure @AdrianGonz97 will share his intention behind that, but personally I do think that this path is quite accurate.

Besides the path you suggest, there are probably at least a thousand different suggestions that are all viable. The goal here is to get you up and running quickly with that new integration. In my opinion, adding a custom alias for `db` is easy and prevents the cli from supporting many different use cases and patterns.

**Comment by AdrianGonz97** [comment]
These modules were added to the `src/lib/server` directory as we want them to be [server-only modules](https://kit.svelte.dev/docs/server-only-modules). Generally, you don't want to execute DB queries outside of the server. Putting the DB related modules into a `server` directory ensures just that - if you try to import them anywhere in the client, SvelteKit will throw a helpful error to tell you that you shouldn't.
