### ISSUE TITLE
add biome 

### ISSUE THREAD

**Issue by sparrowsl** [sveltejs/cli#192]
biome is missing but prettier is available.

**Comment by Hugos68** [comment]
See: https://github.com/sveltejs/cli/issues/193
For more details.

**Comment by manuel3108** [comment]
After some internal discussions, we have decided to not implement this at this point. Feel free to reopen once `biome` added full support for html as well.

**Comment by macmillen** [comment]
https://biomejs.dev/blog/biome-v2-3/

HTML is now fully supported (experimental)

**Comment by pngwn** [comment]
"Supported"

**Comment by pngwn** [comment]
"Fully"

**Comment by Rich-Harris** [comment]
some more context: biome is [completely unusable with svelte](https://bsky.app/profile/rich-harris.dev/post/3m3zzb4nbr22s), and they should not have announced 'full support'

**Comment by hugo-hsi-dev** [comment]
Are there opinions in the svelte team on whether you guys will recommend

1. Continue using ESlint and Prettier
2. Migrate to using Biome (when things actually become stable)
3. oxlint and oxfmt (once it becomes usable with svelte)

**Comment by pngwn** [comment]
We don't have any recommendations until we have working tools. Today only prettier and eslint are usable. 

Hopefully all of these tools will work well with svelte in time, then users will have the luxury of choice.

**Comment by E021ntox** [comment]
With both SvelteKit and the CLI undergoing major new releases, is there any new progress on oxlint + oxfmt integration?
