### ISSUE TITLE
Include Playwright specific `.gitignore` configuration when choosing playwright in `npm create svelte` options

### ISSUE THREAD

**Issue by Pranay-Tej** [sveltejs/cli#197]
### Describe the problem

It'd be nice to have playwright specific `.gitignore` configuration to be included when choosing `Add Playwright for browser testing`  in `npm create svelte` options.

### Describe the proposed solution

Example:

`.gitignore`
```
#Playwright
/test-results/
/playwright-report/
/blob-report/
/playwright/.cache/
/playwright/.auth
```

### Importance

nice to have

**Comment by manuel3108** [comment]
`./test-results/` is the only entry that's added by running `pnpm test`.
This folder is already added to the `.gitgnore`, so there is no additional todo here.
