### ISSUE TITLE
test create-svelte deployments

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/cli#211]
On the Kit repo we used to deploy the template on each PR, e.g. to https://cloudflare.demo.svelte.dev. It's a good way to ensure that things are working end to end. Now that `create-svelte` no longer lives in the `kit` repo, those deployments have started failing.

Not sure if they should live here, or still in Kit because they're really testing the adapters as much as the template, but I wanted to leave a note _somewhere_ before I kill off the project on Cloudflare Pages

**Comment by benmccann** [comment]
The deployments were a pain in the butt. But testing creating a project and then hitting it with playwright would be helpful

**Comment by manuel3108** [comment]
This was done as part of #275. We are not only testing the templates, but additionally most of the addons
