### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by Malix-Labs** [sveltejs/cli#214]
Hey folks !

It would be awesome if the Svelte CLI could also support Deno

Also see https://github.com/denoland/deno/issues/17248

**Comment by Malix-Labs** [comment]
@benmccann I did not find the equivalent of `npx sv create` for Deno

**Comment by AdrianGonz97** [comment]
Could you be a bit more specific? To execute the CLI in Deno, you run `deno run -A npm:sv create` which seemingly works well.

Is the issue that `deno` is missing in the package manager selection prompt? Or that we're possibly missing some scaffolding bits for Deno specific projects (judging by my brief skim of the linked thread referring to the `imports` field in `deno.json`)?

Testing it out, all seems to be working perfectly fine, including running the dev server:
```
➜ deno run -A npm:sv@latest create deno-project
┌  Welcome to the Svelte CLI! (v0.5.7)
│
◇  Which template would you like?
│  SvelteKit demo
│
◇  Add type checking with Typescript?
│  Yes, using Typescript syntax
│
◆  Project created
│
◇  What would you like to add to your project?
│  prettier, eslint
│
◇  Which package manager do you want to install dependencies with?
│  None
│
◆  Successfully setup integrations
│
	...
│
└  You're all set!

➜  cd deno-project
➜  deno install
	...
➜  deno task dev
Task dev vite dev
  VITE v5.4.10  ready in 1266 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
```

**Comment by Malix-Labs** [comment]
>  To execute the CLI in Deno, you run `deno run -A npm:sv` create

Thanks !

I think it should also be documented (see [GitHub Search - `org:sveltejs "npx sv create"`](https://github.com/search?q=org%3Asveltejs%20%22npx%20sv%20create%22&type=code))

> Is the issue that deno is missing in the package manager selection prompt? Or that we're possibly missing some scaffolding bits for Deno specific projects

Both indeed

Maybe also a potential official deno adapter which might have better performance than Deno's node compatibility layer ?

Community adapters :

- https://github.com/pluvial/svelte-adapter-deno
- https://github.com/dbushell/sveltekit-adapter-deno

> for now, selecting `None` and manually installing deps with `deno install` is required as we're waiting on Deno to implement a user_agent in the process's env

Thanks for this information !

Could you please link the related issue ?

What is planned for the svelte cli when that related issue will be closed ?
A new `deno` option choice in the package manager input ?

The proposed dev and build commands also need to be updated

**Comment by lts20050703** [comment]
> Could you please link the related issue ?

@Malix-Labs https://github.com/denoland/deno/issues/25342

**Comment by zoaha** [comment]
would it be possible to omit the 2 tsconfig files at some point when choosing the deno option?

Trying it myself, seems `$lib` is the only thing that breaks, at least in my tiny test project.

**Comment by Malix-Labs** [comment]
that would be nice too indeed.
Also, some imports need to be imported or mapped, such as node process env

**Comment by Malix-Labs** [comment]
This one is particularly annoying and would need to be fixed : 

> Error in svelte.config.js Syntax Error: Cannot use import statement outside a module

https://stackoverflow.com/questions/70588096/error-in-svelte-config-js-syntax-error-cannot-use-import-statement-outside-a-mo

## Workaround

`package.json`
```json
{
	"type": "module"
}
```

**Comment by Malix-Labs** [comment]
> would it be possible to omit the 2 tsconfig files at some point when choosing the deno option?
> 
> Trying it myself, seems `$lib` is the only thing that breaks, at least in my tiny test project.

@zoaha `$env` also doesn't work

Have you found a workaround for `$*` imports ?

**Comment by HighPriest** [comment]
> This one is particularly annoying and would need to be fixed : 
> 
> > Error in svelte.config.js Syntax Error: Cannot use import statement outside a module
> 
> https://stackoverflow.com/questions/70588096/error-in-svelte-config-js-syntax-error-cannot-use-import-statement-outside-a-mo
> 
> ## Workaround
> 
> `package.json`
> ```json
> {
> 	"type": "module"
> }
> ```
> _+ Restart the LSP_

This is odd, as I have a sveltekit-adapter-deno project, which runs completely out of `deno.json`, except **paraglide** which requires `$app` import, so is the only thing that stayed in my package.json:
```
{
 "dependencies": {
  "paraglide":"0.11.0"
}
}
```

**Comment by manuel3108** [comment]
> This one is particularly annoying and would need to be fixed :
> 
> > Error in svelte.config.js Syntax Error: Cannot use import statement outside a module
> 
> https://stackoverflow.com/questions/70588096/error-in-svelte-config-js-syntax-error-cannot-use-import-statement-outside-a-mo
> 
> ## Workaround
> `package.json`
> 
> ```json
> {
> 	"type": "module"
> }
> ```
> 
> _+ Restart the LSP_

@HighPriest How did you generate a project that does not contain this `type: "module"` from the `sv` cli? I just tried all three possible templates, and all of these templates add this line while creating a new project? Or are you talking about an existing application? In that case there is nothing that we should do here. 

> Trying it myself, seems `$lib` is the only thing that breaks, at least in my tiny test project.

@zoaha Can you please explain what exactly breaks in your case? I create a test project and created `$lib/TestComponent.svelte`  and was able to import it from `routes/+page.svelte` without any problems. The LSP seems also happy.

> I think it should also be documented (see [GitHub Search - `org:sveltejs "npx sv create"`](https://github.com/search?q=org%3Asveltejs%20%22npx%20sv%20create%22&type=code))

@Malix-Labs What exactly do you think should be better documented here? If we starting adding a second with for `deno`, people will start asking for every other package manager (pnpm, yarn, new-fancy-package-manger and so on).

**Comment by Malix-Labs** [comment]
> What exactly do you think should be better documented here?

Non straightforward package management install

> deno, people will start asking for every other package manager (pnpm, yarn, new-fancy-package-manger and so on).

They are mostly all straightforward

`deno run npm:sv create` is not

**Comment by HighPriest** [comment]
> @HighPriest How did you generate a project that does not contain this `type: "module"` from the `sv` cli? I just tried all three possible templates, and all of these templates add this line while creating a new project? Or are you talking about an existing application? In that case there is nothing that we should do here.
> 
> > Trying it myself, seems `$lib` is the only thing that breaks, at least in my tiny test project.
> 

I did not.  
I've created the project the same way you do & noted the process [over here](https://amun.pl/blog/post/running-svelte-5-projects-using-deno-in-2024?utm_source=github&utm_id=sveltejs.cli).  
There is nothing stopping you from moving all the devDependencies from `package.json` to `deno.json`, but anything that requires runtime information, still has to be present in the dependencies section of `package.json`.  
Also, if the "type": "module" part of the `package.json` is going to be missing, svelte intellisense is going to complain that _import can only be used in modules_, but the code is going to compile fine.

Fun fact: If you create deno.json & populate it with some dependencies, running `deno add npm:package` is going to add it correctly to deno.json. Running `deno add -D npm:package` is going to add it to devDependencies in package.json. (Which is the opposite of what works for me right now, but... it is what it is.

**Comment by MaxxAls** [comment]
That would be wonderful. CC @matteo-hamaimi

**Comment by MaxxAls** [comment]
> would it be possible to omit the 2 tsconfig files at some point when choosing the deno option?
> 
> Trying it myself, seems `$lib` is the only thing that breaks, at least in my tiny test project.

@zoaha have you found a fix ?

I don't find how to make `$lib` nor `$env` work either

**Comment by dominikg** [comment]
the $lib alias is added to vite config and .svelte-kit/tsconfig.json automatically by sveltekit.  So no, we can't just remove tsconfig files that are required for typescript to understand the project structure. if deno has a different concept for parsing and using typescripts `compilerOptions.paths` it would be on deno to provide a compatibility layer for that. 
We can't start to cater to every custom typescript aware runtime with different configurations, typescript config is complex enough as it is.

**Comment by manuel3108** [comment]
So to summarize: 
* The cli runs within deno via `deno run npm:sv create` without any problems.
* The cli is currently not suggesting `deno` as pm when installing dependencies (see https://github.com/antfu-collective/package-manager-detector/issues/21), but users can workaround this by selecting the trivial "none" option
* The generated projects by this cli run without any problems in deno compatibility mode.
* The docs for using `deno run npm:sv create` could be improved, see #233 
* Deno is not correctly resolving aliases from `.svelte-kit/tsconfig.json` - there is nothing we can do for that, thats up to deno and the workarounds exists, see above.

As far as the cli goes, `deno` is supported, with the two possible improvements mentioned above that can be addressed separately.

**Comment by Malix-Labs** [comment]
Right, it is probably best to split tasks like that, thanks !
