### ISSUE TITLE
Prisma as ORM

### ISSUE THREAD

**Issue by KoesterJannik** [sveltejs/cli#215]
Is there interest in using Prisma instead of drizzle in the cli?
If so, i might give it a try

**Comment by benmccann** [comment]
Not instead of, but as a community adder. We're working on releasing the community api

**Comment by manuel3108** [comment]
Please see #184 for the current status of community adder support, and feel free to subscribe to the issue there. Closing this, as this is nothing we do want to officially support in the future.
