### ISSUE TITLE
Remove lucia

### ISSUE THREAD

**Issue by zlstringham** [sveltejs/cli#217]
The author of lucia is deprecating it. https://github.com/lucia-auth/lucia/discussions/1714

Given that, I think it's a disservice to devs to bootstrap their applications with it today. I'd suggest just removing it. Alternatively, a "lucia-styled" auth could be scaffolded following https://lucia-auth.com/sessions/migrate-lucia-v3

**Comment by AdrianGonz97** [comment]
thanks, but I welcome you to run the integration and see what it does
