### ISSUE TITLE
Adder for sveltekit adapter

### ISSUE THREAD

**Issue by benmccann** [sveltejs/cli#248]
auto should be the default. also offer other official adders

can also use it to customize ignores. see https://github.com/sveltejs/cli/pull/335

**Comment by manuel3108** [comment]
Should this be an adder? Or a question while creating a new project, similar to the `types` question? How would we call the adder?

**Comment by benmccann** [comment]
Interesting. I hadn't considered offering it only during the project setup. I guess that's an option. Though switching out adapter-auto with an adder seems nice

We could call it `sveltekit-adapter`
