### ISSUE TITLE
sv migrate svelte-5

### ISSUE THREAD

**Issue by Jojoshua** [sveltejs/cli#250]
npx sv migrate svelte-5 yields..
You must specify one of the following migrations: package, routes, svelte-4

**Comment by brunnerh** [comment]
That doesn't look right, I get these options:
> You must specify one of the following migrations: package, routes, self-closing-tags, svelte-4, svelte-5, sveltekit-2

What version is the package?

**Comment by Jojoshua** [comment]
Npx sv - v gives me 0.5.11

**Comment by Jojoshua** [comment]
Pretty sure I did use svelte-migrate last time to upgrade to svelte 4. Does it still exist?

**Comment by brunnerh** [comment]
As I said, if it already exists because you used it before, you probably need to upgrade it separately first.

**Comment by Jojoshua** [comment]
> If it already exists because you used it before, you probably need to upgrade it separately first.

Yeah I bet you're right. I will double check, maybe a cache problem. Thanks!

**Comment by benmccann** [comment]
hmm. we already invoke it with `@latest`:

https://github.com/sveltejs/cli/blob/6e2e9da4eb100f033f797c878dccf3f06ddc5225/packages/cli/commands/migrate.ts#L27

**Comment by manuel3108** [comment]
Closing, since we are already using `@latest` and this has been the only report.
