### ISSUE TITLE
Create a Svelte project without kit

### ISSUE THREAD

**Issue by jzillmann** [sveltejs/cli#260]
I would like to setup a project using Svelte, without using Kit!

Is that something you consider adding to the cli ?

**Comment by benmccann** [comment]
Closing as duplicate of https://github.com/sveltejs/cli/issues/168

Can you share what your usecase is though?

**Comment by jzillmann** [comment]
Lot of times I just use plain svelte. Usually I already have a backend, e.g. tauri.
Still could use kit, but it doesn't compel to me for some reason

**Comment by benmccann** [comment]
What router do you use in that case?

**Comment by jzillmann** [comment]
So far...
- none (e.g. for pure tauri apps)
- `svelte-routing`
- `svelte-pathfinder`
