### ISSUE TITLE
fix `storybook` tests on windows in ci

### ISSUE THREAD

**Issue by manuel3108** [sveltejs/cli#293]
In #275 we had severe problems with the storybook tests on windows. They were failing with obscure error message while running `pnpm dlx storybook@8.3.6`. Those failing tests mostly occurred on windows, but from time to time also on ubuntu. Never on mac.

Tests work flawlessly locally on windows; thus we decided to skip them ci for now

**Comment by JReinhold** [comment]
Let me know if I can assist in any way here.

**Comment by AdrianGonz97** [comment]
It's tough to pinpoint the exact issue, but some error info we've been able to get: https://github.com/sveltejs/cli/actions/runs/11806879168/job/32892430989?pr=181#step:8:168

**Comment by AdrianGonz97** [comment]
@JReinhold 

I managed to reduce it down into a minimal repro: https://github.com/AdrianGonz97/storybook-ci-repro

It appears that it doesn't like to run separate processes of `storybook init` concurrently.

**Comment by manuel3108** [comment]
> I managed to reduce it down into a minimal repro: https://github.com/AdrianGonz97/storybook-ci-repro
> 
> It appears that it doesn't like to run separate processes of `storybook init` concurrently.

Great. Was also able to reproduce this in a linux based codespace just now!

**Comment by AdrianGonz97** [comment]
> Should we try running the storybook test non concurently?

Already covered in https://github.com/sveltejs/cli/pull/181/files#diff-88b82b064ede32a2332fd0d35f0f01326479ad0ff68248247c513c40838072caR10-R13

**Comment by manuel3108** [comment]
Ohh great Since this is also happening on ubuntu from time to time, should we just remove the concurrent tests for `storybook` altogether?

**Comment by AdrianGonz97** [comment]
I think we can just leave it alone for now. If it starts to get annoying again on the other platforms, then we can start considering to only running it sequentially in CI

**Comment by manuel3108** [comment]
And for the sake of protocolling it somewhere, this just happend to me for the first time on `macOs` as well. https://github.com/sveltejs/cli/actions/runs/11843814850/job/33005611663?pr=303

**Comment by JReinhold** [comment]
Are you okay with fixing it in your CI, not running them concurrently?

Because it doesn't sound like anything a regular user would do (you're probably the first ever to discover this), so sinking time into figuring out the issue on the Storybook side is a hard sell.

**Comment by AdrianGonz97** [comment]
> Because it doesn't sound like anything a regular user would do (you're probably the first ever to discover this)

Based on the error, there may be a few more folks that ran into this (or something similar) as well: https://github.com/storybookjs/storybook/issues?q=sort%3Aupdated-desc%20is%3Aissue%20is%3Aopen%20Error%3A%20EBUSY%3A%20resource%20busy%20or%20locked

> Are you okay with fixing it in your CI, not running them concurrently?

For sure! It's certainly not a dealbreaker since we have a workaround now

**Comment by manuel3108** [comment]
Running them sequentially hasn't caused any trouble in the last two weeks, closing.
