### ISSUE TITLE
better add command

### ISSUE THREAD

**Issue by cognominal** [sveltejs/cli#297]
Setting up stuff was a nightmare for people not familiar with the web ecosystem. sv/cli doing it is great. Thx.
The implementation of my proposition would help the beginners without bothering the experts:

* For each package to add, provide a oneliner description
* indicate the packages already installed by a blue checkbox

**Comment by manuel3108** [comment]
> * For each package to add, provide a oneliner description

We have done so many revision of that, that i stopped counting. The current implementation is both minimal and gives you a direct link to the site, in case you don't know what this or that tool is doing.

One of our previous iterations was the one below, that you can try yourself with `pnpx svelte-add`. Please don't run it further than the initial questions tho, as the tool is outdated.
![image](https://github.com/user-attachments/assets/70e50874-d1a0-47b2-a5a1-04079c75778c)

The problem with this is that it feels clunky and requires much vertical space. Adding a description to the line might work, but why not link to their website directly, where they can describe themself.

> * indicate the packages already installed by a blue checkbox

This might be an interesting one. For some tools, this is pretty easy to detect based on the installed packages, but if I do remember correctly from the past, we had a problem with at least one tool, where this was not straightforward. Thus we decided to leave it.
