### ISSUE TITLE
Following HTML5 specification for meta and link in app.html

### ISSUE THREAD

**Issue by shinokada** [sveltejs/cli#318]
### Describe the bug

According to [HTML5 specification](https://www.w3.org/TR/2011/WD-html5-20110405/semantics.html#document-metadata), `meta` and `link` do not have the trailing slash.

So shouldn't it be 
```
<meta charset="utf-8">
<link rel="icon" href="%sveltekit.assets%/favicon.png">
<meta name="viewport" content="width=device-width, initial-scale=1">
```

rather than:
```
<meta charset="utf-8" />
<link rel="icon" href="%sveltekit.assets%/favicon.png" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
```

### Reproduction

Check `src/app.html`.

### System Info

```shell
n/a
```

### Severity

annoyance

**Comment by benmccann** [comment]
Closing per the last comment
