### ISSUE TITLE
Support `orogene` package manager

### ISSUE THREAD

**Issue by notramo** [sveltejs/cli#330]
https://github.com/orogene/orogene

`orogene` doesn't have an `orogene x` command yet, so it can not be used to run `orogene x sv create`, but it could be offered in the package manager selection step. `orogene apply` is the command to run.

**Comment by Conduitry** [comment]
I don't think we want to be offering as a blessed option something that declares itself to be under heavy development and not ready for production yet. If someone really wants to use this package manager, they'll be able to figure out how to do so.

**Comment by benmccann** [comment]
It had only a single commit in 2024, so it seems it's both not ready for production and not getting there anytime soon

**Comment by notramo** [comment]
Then why not remove Bun? It's nearly at the same level of maturity as `orogene` or `cotton`. It's definitely not production ready. Current use cases include benchmarks, and hobby projects. So it seems this Svelte CLI has no problem with non-production-ready options.

Also, all of `pnpm`, `bun`, `orogene` and `cotton` offer more production-ready dependency resolution algorithm than `npm` because a package manager that introduces [doppelganger dependencies](https://rushjs.io/pages/advanced/phantom_deps/) is very much far from production-ready. So, `npm` should be removed too, leaving us with `pnpm` and `yarn`.

Also worth noting that `orogene` and `cotton` offer performant package management with any runtime, including Node. Currently, one can choose between installing an entire runtime/linter/bundler/etc (Bun and Deno) to get performant package management, or getting stuck with `pnpm` if they want to use Node.

Regarding development activity, I'm sure if these projects would get the same exposure as Bun or Deno, development would be more active.

**Comment by benmccann** [comment]
`bun` has 74k stars. `cotton` has 290. We're not adding obscure package managers. It just adds additional overhead for the vast, vast majority of users who will never use them
