### ISSUE TITLE
vitest install error: No overload matches this call

### ISSUE THREAD

**Issue by mxfactorial** [sveltejs/cli#341]
#### version
sv@0.6.6

#### steps
1. open a [typescript gitpod](https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node)
1. select continue button to create a new workspace
1. wait for the editor to appear 
1. cntrl c the init task to cancel or open a new terminal 
1. `rm -rf ./* ./.*` to remove directory contents
1. `npx sv create .`
1. `y` to install sv@0.6.6
1. choose:
    1. SvelteKit minimal
    1. Typescript syntax
    1. **vitest**
    1. npm
1. open vite.config.ts

#### observed
`sveltekit()` errors with 'No overload matches this call.'

<img width="1077" alt="Screenshot 2024-12-02 at 8 38 16 PM" src="https://github.com/user-attachments/assets/5c64da8e-fc4b-4058-b28e-0c532598927a">

**Comment by manuel3108** [comment]
The core problem here is that we are switching the type for the vite config from `vite` to `vitest` and it looks like `vitest` currently does not support plugins of type `Promise<whatever>`

```js
// without vitest
import { defineConfig } from 'vite';

// with vitest
import { defineConfig } from "vitest/config";
```

Still trying to find any relevant issue. Currently only found this discussion in vite repo: https://github.com/vitejs/vite/discussions/8509

Look's like the vitest config has not been updated to match vite 6

**Comment by manuel3108** [comment]
Did not find anything meaningful, therefore created this issue: https://github.com/vitest-dev/vitest/issues/7014

**Comment by AdrianGonz97** [comment]
The mismatch in types is because `vitest` [reverted support for Vite 6 in `2.1.7`](https://github.com/vitest-dev/vitest/releases/tag/v2.1.7). 

Types can be fixed by reverting back to `2.1.6` or using `pnpm.overrides` to force `vitest` to use Vite 6. Though, I would just ignore the type error for now until they fix things on their end in a new release.

**Comment by dominikg** [comment]
see https://github.com/dominikg/vitest-example-svelte5/pull/1  for a setup that works with vite@6, vitest@3 beta and latest sveltekit/svelte

**Comment by Oudwins** [comment]
This is still happening with the default sv template. At least on npm. Let me check pnpm

**Comment by dominikg** [comment]
for pnpm it is either `resolutions` or `pnpm.overrides` as a key in package.json, see https://pnpm.io/package_json#pnpmoverrides
https://pnpm.io/package_json#resolutions

**Comment by Oudwins** [comment]
Ah, I see. My bad. I will say that updating to vitest 3.0 beta also works

**Comment by manuel3108** [comment]
We have reverted the changes to use `vite@6` while creating new projects, since `vitest@3` will only be released in January. For newly created projects, this is no longer an issue. All others can use a workaround provided above.
