### ISSUE TITLE
ESLint config imports a transitive dependency that is not installed (pnpm 10)

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/cli#374]
We import `@eslint/js` but never actually add it to `package.json`, so linting actually fails even on a minimal fresh setup:
```
$ pnpx sv create sample
┌  Welcome to the Svelte CLI! (v0.6.9)
│
◇  Which template would you like?
│  SvelteKit minimal
│
◇  Add type checking with Typescript?
│  No
│
◆  Project created
│
◇  What would you like to add to your project? (use arrow keys / space bar)
│  eslint
│
◇  Which package manager do you want to install dependencies with?
│  pnpm
│
◆  Successfully setup add-ons
│
◆  Successfully installed dependencies
│
◇  Project next steps ─────────────────────────────────────────────────────╮
│                                                                          │
│  1: cd sample                                                            │
│  2: git init && git add -A && git commit -m "Initial commit" (optional)  │
│  3: pnpm dev --open                                                      │
│                                                                          │
│  To close the dev server, hit Ctrl-C                                     │
│                                                                          │
│  Stuck? Visit us at https://svelte.dev/chat                              │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
└  You're all set!
$ cd sample
$ pnpm lint

> sample@0.0.1 lint C:\Users\glitterforce\Documents\sample
> eslint .


Oops! Something went wrong! :(

ESLint: 9.17.0

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from C:\Users\glitterforce\Documents\sample\eslint.config.js
Did you mean to import "@eslint/js/src/index.js"?
    at packageResolve (node:internal/modules/esm/resolve:857:9)
    at moduleResolve (node:internal/modules/esm/resolve:926:18)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49)
 ELIFECYCLE  Command failed with exit code 2.
```

**Comment by GrygrFlzr** [comment]
Additional findings:

This only occurs on pnpm 10, not pnpm 9. Will file a regression to pnpm.

**Comment by manuel3108** [comment]
See discussion in #375

**Comment by GrygrFlzr** [comment]
Posted detailed issue to pnpm/pnpm#8913 for further information.

**Comment by GrygrFlzr** [comment]
Based on pnpm/pnpm#8378 it seems that not-hoisting the eslint transitive dependencies is an intended breaking change. Specifically, prior versions of pnpm would hoist any packages with names containing `eslint` or `prettier` by default. pnpm 10 no longer includes that default hoisting.

Given that pnpm 10 is already in its first Release Candidate, I expect this will become an immediate problem for svelte CLI users.

Should we really rely on `@eslint/js` (or any other transitive dependency) to be automatically visible? The less fragile approach is to explicitly state them as dependencies if they are used in our configs as per #375, no?

The other short term alternative is to re-add the hoisting to our `.npmrc` but that seems short-sighted.

**Comment by benmccann** [comment]
Explicitly listing the dependency makes sense to me

**Comment by Conduitry** [comment]
https://pnpm.io/npmrc#public-hoist-pattern (which as of this writing still contains the v9 description and defaults, which I expect will change in v10).

> Unlike `hoist-pattern`, which hoists dependencies to a hidden modules directory inside the virtual store, `public-hoist-pattern` hoists dependencies matching the pattern to the root modules directory. Hoisting to the root modules directory means that application code will have access to phantom dependencies, even if they modify the resolution strategy improperly.

> This setting is useful when dealing with some flawed pluggable tools that don't resolve dependencies properly.

In v9 the default is `['*eslint*', '*prettier*']`, and in v10 the default is `[]`.

I know that Prettier changed its plugin resolution mechanism in v3. I imagine ESLint did as well as part of all of their recent rearchitecting of everything. pnpm presumably decided they didn't need to include these default workarounds anymore (in fact, it sounds like in some cases they were causing problems) and decided that anyone who did still need them could be responsible for setting them themselves.

**Comment by Sitronik** [comment]
> https://pnpm.io/npmrc#public-hoist-pattern (which as of this writing still contains the v9 description and defaults, which I expect will change in v10).
> 
> > Unlike `hoist-pattern`, which hoists dependencies to a hidden modules directory inside the virtual store, `public-hoist-pattern` hoists dependencies matching the pattern to the root modules directory. Hoisting to the root modules directory means that application code will have access to phantom dependencies, even if they modify the resolution strategy improperly.
> 
> > This setting is useful when dealing with some flawed pluggable tools that don't resolve dependencies properly.
> 
> In v9 the default is `['*eslint*', '*prettier*']`, and in v10 the default is `[]`.
> 
> I know that Prettier changed its plugin resolution mechanism in v3. I imagine ESLint did as well as part of all of their recent rearchitecting of everything. pnpm presumably decided they didn't need to include these default workarounds anymore and decided that anyone who did still need them could be responsible for setting them themselves.

I encountered the same problem, an example of the correct syntax in .npmrc:
```
public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*prettier*
```
After applying this configuration there will be no problems with eslint and prettier
